name: Annual Branch Merge

on:
  schedule:
    - cron: '0 0 7 * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge branch into master
        run: |
          git config user.name "zakkcodes"
          git config user.email "zachary.stranger@proton.me"
          git checkout master
          git merge --squash origin/linnforsman-202X
          git commit -m "README UPDATE"
          git push origin master
